# Generated by Django 2.1.1 on 2018-10-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
    ]
