# Generated by Django 2.1.1 on 2018-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0003_auto_20181002_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_image',
            field=models.ImageField(upload_to='MusicDownload/static/MusicDownload/images/'),
        ),
    ]
