# Generated by Django 2.1.1 on 2018-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0007_auto_20181003_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='actual_track',
            field=models.FileField(upload_to=''),
        ),
    ]
