# Generated by Django 2.1.1 on 2018-10-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0008_auto_20181003_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='actual_track',
        ),
    ]
