# Generated by Django 2.1.1 on 2018-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0012_auto_20181003_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='actual_track',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
