# Generated by Django 2.1.1 on 2018-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0013_tracks_actual_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_length',
            field=models.FloatField(),
        ),
    ]
