# Generated by Django 2.1.1 on 2018-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0014_auto_20181005_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_language',
            field=models.CharField(max_length=100),
        ),
    ]
