# Generated by Django 2.1.1 on 2018-10-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0015_auto_20181005_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='track_language',
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_length',
            field=models.IntegerField(),
        ),
    ]
