# Generated by Django 2.1.1 on 2018-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0016_auto_20181005_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_genre',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracks',
            name='track_language',
            field=models.CharField(default='English', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracks',
            name='track_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_length',
            field=models.FloatField(),
        ),
    ]
