# Generated by Django 2.1.1 on 2018-10-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicDownload', '0017_auto_20181005_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_language',
            field=models.CharField(max_length=50),
        ),
    ]
